baseURL = "https://kdimas12.netlify.app/"
languageCode = "en-us"
title = "sadim."
copyright = "{year}"

theme = "exampleTheme"

[params]
  dateFormat = "Jan 2 2006"
  homeText = "I just made a Hugo blog from scratch."

[permalinks]
  posts = "/:filename/"

[taxonomies]
  tag = "tags"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3