baseURL = "https://kdimas12.netlify.app/"
languageCode = "en-us"
title = "sadim."

theme = "exampleTheme"

[params]
  dateFormat = "Jan 2 2006"
  homeText = "I just made a Hugo blog from scratch."

[permalinks]
  blog = "/:filename/"

[taxonomies]
  tag = "tags"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1